SilentVoid13/Templater

- package.json
- src/i18n.ts
- src/main.ts
- src/settings.ts
Hey @SilentVoid13 
great plugin! One thing I was missing is the ability to change the locale so that the dates are formatted with (in my case) german week and month names.
I added an option to the settings to let the user choose their locale. The dropdown shows all locales available in moment.js.
> Add option to change locale

- src/settings.ts
It's me again 😉
Thanks for merging my other PR. After restarting Obsidian I noticed that some of my settings were gone.
I've seen that you're saving the settings in the `onunload` handler but that doesn't seem to work. I've added `saveData` calls to all settings that were missing it. I don't know if this is the way to go, but I've seen it in other plugins.
> Save settings after each change

- data.json
- src/internal_templates.ts
(This is my first ever pull request for a public repo so if I did something wrong feel free to let me know). 
I use your Templater a lot, but I also like to create notes in the future for certain reasons. I use a breadcrumb linking syntax at the top of my notes for yesterday and tomorrow, however, your `tp_yesterday` and `tp_tomorrow` do not work unless you create the note for 'today' 
This functionality I am requesting be added will allow you to create a 'previous' and 'next' day links. 
The syntax is `{{tp_nextday}}` and `{{tp_prevday}}`.
It is based on the title of the note that is being created to get the 'base date' to generate the next and previous days. Because of this I added a check in the code to verify that the title is a valid ISO8601 date. 
I then use moments built in …
> Adding Internal Templates for NextDay and PrevDay

- src/fuzzy_suggester.ts
- src/main.ts
The added command allows you to replace any templates in your active file.
This is useful if the file has already been created and you just want to add something to it using the custom templates.
add a Templater template (such as ```{{tp_now}}``` anywhere in an open document, and run the Replace in Open File command, to expand that template.
> Added "Replace" in active file command

- src/Settings.ts
- src/Templater.ts
- src/Utils.ts
- src/main.ts
Addresses https://github.com/SilentVoid13/Templater/issues/200
- requires `trigger_on_file_creation` to be enabled
- only runs on files with no content
<details>
<summary>For an example of what a default template might look like:</summary>
```js
<%*
// This logic is actually defined as a Script User Function
// so I can just do:
// const defaultTemplate = tp.user.getDefaultTemplate(tp);
const fallback_template = "[[assets/templates/fallback]]";
const config = [
{ 
regex: /^\d{4}-\d{2}-\d{2}$/,
template: "[[assets/templates/daily_note]]"
},
{ 
regex: /^\d{4}-\d{2}-W\d{2}$/,
template: "[[assets/templates/weekly_note]]"
},
{ 
regex: /^\d{4}-\d{2}$/,
template: "[[assets/templates/monthly_note]]"
},
{
regex: /^\d{4}-Q\d{1}$/,
template: "[[assets/templates/quarterly_note]]"
},
{
regex: …
```
> feat: Allow users to provide a default template for empty new files

- docs/docs/internal-variables-functions/internal-modules/config-module.md
This commit updates the doc links to point to the correct lines before the 1.8.0 release as the contents of the file they were referencing has changed.
> Update doc references for internal config module

- docs/docs/user-functions/overview.md
I ran into #223 but had to come to the GitHub issues to see that it was a problem. I added this as a temporary caution  until user functions are available.
> Add caution to user functions for mobile

- .gitignore
- docs/docs/settings.md
- src/FolderTemplate.ts
- src/Settings.ts
- src/Templater.ts
- src/Utils.ts
Implements folder-based templates similar to the functionality provided
by Vinzent03's `Hotkeys for Templates` plugin.
Since Templater also implements hotkeys directly, I think most people
will now be able to get all the functionality from Hotkeys for Templates
using just Templater.
Since this functionality supercedes the empty file template functionality,
that has been removed.
Fixes: #326
> Feat: Folder Templates

- src/core/Templater.ts
- src/editor/Editor.ts
fixes #564
This fixes a bug where the focus is stolen away from the `rename` input to place it in the document.
Instead, we set the cursor position _first_. Then we trigger the rename. After pressing <kdb>Enter</kbd> from the rename box, the cursor will return to the initial cursor_jump destination as expected.
> fix: Activate cursor jump before renaming file

- src/core/Templater.ts
- src/obsidian.d.ts
Other plugins can listen for the workspace events `templater:overwrite-file` and `templater:new-note-from-template` to hook into templater and provide additional functionality
> feat: trigger events on template overwrite, new file creation

- src/core/functions/internal_functions/system/PromptModal.ts
fixes #256 by not calling `new TemplaterError` when rejecting the Modal.
> comment out `reject` throwing a new TemplaterError to avoid freezing app

- src/core/functions/user_functions/UserFunctions.ts
There was an issue where if you tried to use user scripts on mobile devices, it would throw an error saying that your script did not exist. It would still detect your user scripts in the settings, but you would not be able to generate any templates. Removing the check to only allow user scripts for desktop seems to have resolved the issue.
This is working for me on my personal Android phone. I am not sure which mobile device caused this to be solely allowed for desktop prior, but it may be that Obsidian has been updated in such a way that the issue has gone away.
fix #586
Changes Made:
- Removed Platform import from Obsidian and using it to check if the current platform is desktop in `UserFunctions.ts`
> Allow User Scripts on Mobile

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
I think questions need to be asked in the Discussions feature and issues should be limited to feature requests and bug reports only.
Also I don't think we should auto-assign all issues to SilentVoid
> delete question template from Issues & remove auto-assign to SilentVoid

- src/main.ts
- src/settings/Settings.ts
Enhancement #647 I suggested recently.
Add a plugin option to show or hide the sidebar/ribbon icon. There are other ways, including even [another obsidian extension](https://github.com/phibr0/obsidian-customizable-sidebar) with an option to hide the Templater icon. I think it makes more sense and is better for the extension itself to offer that option.
Changes Made:
- Added boolean setting enable_ribbon_icon, default true, toggle option hides/shows icon.
- Added check to see if setting is true before adding icon in main.
> Add option to show/hide Templater ribbon icon

- manifest.json
- src/core/functions/internal_functions/system/InternalModuleSystem.ts
- src/core/functions/internal_functions/system/PromptModal.ts
- styles.css
I've added a new multi-line input prompt inspired by chhoumann/QuickAdd. See [here](https://github.com/chhoumann/quickadd/blob/master/src/gui/GenericWideInputPrompt/GenericWideInputPrompt.ts) for original.
It can be invoked using
```js
let default_value = "Original";
let prompt_text = "Prompt Title Here";
let throw_on_cancel = false;
let multi_line = true;
tR += await tp.system.prompt(prompt_text, default_value, throw_on_cancel, multi_line);
```
Sample:
This is an optional variable that shouldn't introduce any breaking changes. I haven't had a chance to test this on mobile.
Note: the event handler for mobile behaves slightly differently. For multi-line inputs, the Submit button must be used as the enter key moves the cursor to the next line.
Please let me know if there's any cleanup I …
> Feature: multiline input with `tp.system.prompt`

- src/core/functions/internal_functions/system/PromptModal.ts
For some reason, the prompt has a placeholder and a value set. In the last release, the placeholder was set after the value, overwriting any default_value set by the user. This PR changes the order back.
fixes #801
> fix: prompt default_value and placeholder order

- docs/documentation.toml
- src/core/functions/internal_functions/web/InternalModuleWeb.ts
fixes #792 
alternative to #793  and #794 
This adds an optional boolean argument to `tp.web.random_picture`: `include_siz`
When true, the size specified in the first argument of the function will be included in the response image markdown:
When false the size won't be included in output. The default value is false to replicate pre 0.13.0 behaviour
> feat: add optional argument to include size in tp.web.random_picture

- src/core/functions/internal_functions/system/PromptModal.ts
Issue where it is undefined if you just accept the default string. Happens with all combo of options multi line true/false... error throw true/false. See video.
https://user-images.githubusercontent.com/64155612/189000550-c201fb6c-01ed-4d26-8a9f-eab062308a72.mp4
> Fix PromptModal default value needs to be set to this.value on load

- src/core/functions/internal_functions/file/InternalModuleFile.ts
- tests/InternalTemplates/file/InternalModuleFile.test.ts
Repairs regression to move support on mobile added by #444.
Preserves behavior of second parameter, and ensures target directory exists first.
> fix: move on mobile using obsidian api (not path)

- src/core/Templater.ts
See my comment from https://github.com/SilentVoid13/Templater/issues/716#issuecomment-1242573930
- I've done a bit of testing but would appreciate others verify that this doesn't break anything. I am not familiar with this codebase.
- I chose `300ms` as the max threshold between file creation and opening - works on my machine, but not sure if it might break on slower machines?
- I wonder if a similar event+timeout approach could be used to eliminate the need for the `await delay(300)`
Fixes #716, fixes #554
> fix: don't trigger on creation unless new file is opened in a pane

- src/core/functions/internal_functions/file/InternalModuleFile.ts
Swaps current implementation of `tp.file.exists` to use the internal `exists` method.
**This is a breaking change as it turns `tp.file.exists` into an async function.
fixes #817
> fix!: use app.fileSystemAdapter.exists for tp.file.exists

- src/core/functions/internal_functions/web/InternalModuleWeb.ts
This PR changes the old and now deprecated Unsplash API endpoint to the new unsplash API.
Because the new API requires authentication, I created a small express add hosted at https://templater-unsplash.fly.dev/ which acts as a proxy for the unsplash api. This way the Auth Key won't be exposed on the client.
The server-side code can be reviewed here: https://github.com/shabegom/templater-unsplash-proxy
The one potential issue is that the API has a rate limit of 50 images per hour unless you apply for production-level access. Some of the API guidelines make production-level access undesirable. To try and loosely adhere to the guidelines, the text of a random_picture will now include attribution to the photographer.
> fix: change to new unsplash api

- src/core/functions/internal_functions/file/InternalModuleFile.ts
As it says in the title. The way that it gets the root path of the vault is a little messy, but does work.
> Make tp.file.path(...) work on mobile

- docs/src/internal-functions/internal-modules/file-module.md
tp.file.exists() is async, but the docs are not reflecting that. Also it requires full path as an argument to avoid collisions of files with same name in different folders
> Fix tp.file.exists() example

- docs/src/internal-functions/internal-modules/date-module.md
- docs/src/internal-functions/internal-modules/file-module.md
- docs/src/internal-functions/internal-modules/frontmatter-module.md
- docs/src/internal-functions/internal-modules/system-module.md
- docs/src/internal-functions/internal-modules/web-module.md
Use \<pre\> tag to escape all content that is not meant to have syntax highlighting.
Add syntax highlighting to frontmatter-module.
Closes #852
> Escape apostrophes and keywords in examples in docs closes #852

- src/core/Templater.ts
A hard coded fix for #873.
Based on a quick analysis of my vault, I propose to hard coded file size limit of 10000 to skip the on file create parsing of large files.
I have 5675 markdown files in my vault. Over 90% percent of these have a size below the proposed 10000 size limit.
> fix: parsing freezes on large files

- package.json
To run this script requires installing mdbooks following the steps here https://rust-lang.github.io/mdBook/guide/installation.html
We may want to consider adding some documentation (in the README or elsewhere) to explain that there needs to be an installation process first.
I don't think we'd want to add an script to install mdbooks, since we may not know where the user wants to install the binary, but if y'all feel otherwise I can add an install script, just think it needs some discussion first before we add that.
> Add docs-dev script for running mdbooks locally

- docs/documentation.toml
- docs/src/internal-functions/internal-modules/file-module.md
- src/core/functions/internal_functions/file/InternalModuleFile.ts
Addresses #878 in 2 ways:
1) Fixes documentation to reflect that tp.file.exists requires a full path. 
2) Adds a call to normalizePath() inside exists() function so that templates can work across Windows and *nix OS'.
> Bug: tp.file.exists in Obsidian v1.0.0 always returns false for files;

- src/editor/Editor.ts
Disables syntax highlighting on mobile devices because it seems to break live preview rendering.
> fix: syntax highlighting breaks live preview on mobile.

- docs/src/commands/execution-command.md
- docs/src/internal-functions/internal-modules/system-module.md
Currently, the Execution commands cannot save the output of a suggester or prompt to a variable w/o an await. Added an example and some content about the change.
> Added content to help files. Await on tp.system cmds

- docs/src/commands/execution-command.md
quick fix spelling error I didn't catch in the last docs merge
> chore: fix spelling mistake

- src/core/Templater.ts
- src/core/functions/internal_functions/file/InternalModuleFile.ts
- src/editor/Autocomplete.ts
- src/editor/CursorJumper.ts
- src/editor/Editor.ts
Allow executing templates in notes in `.canvas` files (fixes #1034).
1. Replace all instances of `app.workspace.getActiveViewOfType()` with `app.workspace.activeEditor`.
2. Replace all instances of `app.workspace.getActiveFile()` with `app.workspace.activeEditor?.file`.
> Allow executing templates in notes in .canvas files

- src/core/Templater.ts
Remove unneeded delay on file creation after version 1.0 of Obsidian.
> I believe that templater can remove that 300ms delay now. The reason was actually a problem in Obsidian core that was fixed a long time ago.
> Basically, the daily notes core plugin would create an empty file, then modify the empty file with your daily note template.
> The issue was that the ‘created’ event was fired before the daily note template was applied, so Templater needed to work around that issue.
> I think that hasn’t been a problem since around 1.0 of Obsidian. Now all the core plugins create the file with the contents already applied in a single filesystem call.
Liam C., Obsidian Team
https://forum.obsidian.md/t/why-i-need-to-wait-a-random-amount-of-time-after-creating-a-file-with-teplater/66066/8
> Remove unneeded delay on file creation on newer versions

- src/editor/CursorJumper.ts
Instead of just allowing between 0-2 characters for tp.file.cursor, allow as many characters as the user wants.
This fixes #956.
> Allow many more cursors

- docs/documentation.toml
- docs/src/internal-functions/internal-modules/config-module.md
- docs/src/internal-functions/internal-modules/date-module.md
- docs/src/internal-functions/internal-modules/file-module.md
- docs/src/internal-functions/internal-modules/system-module.md
- docs/src/internal-functions/internal-modules/web-module.md
Encoding function arguments as an array of tables instead of a table of tables in `documentation.toml` allows us to iterate over them in the order declared instead of being sorted alphabetically in the docs. 
Works correctly in my local build of the docs.
> Preserve order of function arguments in documentation

- src/types.ts
in `suggest.ts`, there's an error message "Property 'dom' does not exist on type 'App'." in [line 153](https://github.com/SilentVoid13/Templater/src/settings/suggesters/suggest.ts#L153)
this patch fixes the issue
> fix: define app.dom

- src/editor/Autocomplete.ts
- src/editor/Editor.ts
- src/editor/TpDocumentation.ts
This fixes #840 by returning the files in the user's user_scripts_folder as autocomplete suggestions.
Future enhancement: Support adding other documentation parameters (description, example, etc.)
> Fix autocomplete user functions

- docs/documentation.toml
- docs/src/SUMMARY.md
- docs/src/internal-functions/internal-modules/hooks-module.md
- docs/src/internal-functions/overview.md
- src/core/Templater.ts
- src/core/functions/FunctionsGenerator.ts
- src/core/functions/internal_functions/InternalFunctions.ts
- src/core/functions/internal_functions/InternalModule.ts
- src/core/functions/internal_functions/config/InternalModuleConfig.ts
- src/core/functions/internal_functions/date/InternalModuleDate.ts
- src/core/functions/internal_functions/file/InternalModuleFile.ts
- src/core/functions/internal_functions/frontmatter/InternalModuleFrontmatter.ts
- src/core/functions/internal_functions/hooks/InternalModuleHooks.ts
- src/core/functions/internal_functions/system/InternalModuleSystem.ts
- src/core/functions/internal_functions/web/InternalModuleWeb.ts
- src/editor/TpDocumentation.ts
- src/main.ts
- src/types.ts
Add hooks module and `on_all_templates_executed` function for that module.
Link to documentation [here](https://silentvoid13.github.io/Templater/internal-functions/internal-modules/hooks-module.html).
> Add hooks module

- src/core/functions/internal_functions/web/InternalModuleWeb.ts
This PR proposes two changes to the `generate_daily_quote` function:
1. Removal of the `<cite>` element from quote formatting. According to the HTML specification, the <cite> tag defines the title of a creative work (e.g., a book, a poem, a song, a movie, etc.), and it's not intended for citing individuals. Therefore, this change aligns with best practices for HTML and semantic web.
2. Update of quote formatting to use Obsidian callouts. This change provides a more visually appealing and distinguishable format for quotes compared to the generic markdown quote syntax within Obsidian. (With this change, the author’s name stays on a new line, even with strict line breaks enabled.)
Original:
Proposed:
Here are the original and proposed changes:
Original:
```typescript
const new_content = `> …
```
> Enhance Quote Formatting and Semantic Correctness in `generate_daily_quote`

- src/editor/Editor.ts
- src/handlers/EventHandler.ts
Fixes the broken highlighting in `1.5.x`. Changes internally had changed the priority of the default `hypermd` highlighter, so when the Templater mode was created it was lower priority.
In this PR I force it to use `Prec.high(...)` and hence when it's enabled it now works. It also changes things to use the new mechanism for loading and unloading the highlighter, given the old one has been removed entirely. The toggles in settings still work in real-time.
Finally, I should note that it will no longer work in the CM5 editor, but given that this is removed by Obsidian 1.5.x I do not think this is a problem.
Many thanks to Licat for the pointer regarding the priority changes!
Closes #1251
> Force the priority higher to override hypermd

- pnpm-lock.yaml
Regenerated pnpm-lock.yaml file in order to upgrade downstream packages to resolve vulnerabilities with those downstream dependencies.
Before:
After:
> Regenerate pnpm-lock.yaml file to resolve downstream vulnerabilities

- .github/workflows/deploy.yml
- .github/workflows/release.yml
The version of each action has been brought up to date at this time.
warning is below
This PR is for `actions/checkout`.
> To resolve warnings I get when using Node12 (actions/checkout)

- src/settings/Settings.ts
Follow the official [Obsidian Style Guide](https://help.obsidian.md/Contributing+to+Obsidian/Style+guide#Sentence%20case)'s guidelines, use sentence case for setting names
> Use sentence case for settings per Obsidian Style Guide

- src/handlers/CommandHandler.ts
- src/main.ts
- src/settings/Settings.ts
Update settings tab to follow UI design guidelines: https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#UI+text
Also removed the ribbon setting, since Obsidian itself now has a setting for this.
> Follow UI design guidelines

- src/handlers/FuzzySuggester.ts
This pull request builds upon the work done by @DraggonFantasy in https://github.com/SilentVoid13/Templater/pull/1078. It includes the following additional changes:
- Removes settings, and removes requirements for settings in `getItemText()` func
Credit to @DraggonFantasy for the initial work.
Fixes https://github.com/SilentVoid13/Templater/issues/1223
> Return Relative Paths of Templates in Fuzzy Suggester Prompt

- src/utils/Utils.ts
An oversight within https://github.com/SilentVoid13/Templater/pull/1418.
Now sorts suggestor files by path as apposed to solely basename. 
Before:
After: 
---
This is a great feature, because ultimately, it simply uses the folder structure that matches the templates folder. So if you want to keep a single flat heierarchy, have no folders!
> Sort Files by Path

- README.md
This pull request corrects a broken URL related to the contributions section in the README file.
> Fixed broken url link in README

- docs/documentation.toml
- src/core/functions/internal_functions/web/InternalModuleWeb.ts
`tp.web` function to make HTTP requests. Optionally, you can specify a path to extract specific data from the response.
```
<% tp.web.request("https://jsonplaceholder.typicode.com/todos", "0.title") %>
```
Here we are making a call to the `todos` endpoint and we are getting the `title` of the first element.
> feat: new web function to make http requests

- docs/documentation.toml
- src/core/functions/internal_functions/file/InternalModuleFile.ts
This should clarify behaviour whilst preserving back-compatibility.
This is a best-of solution that will hold until a better one is developed.
fixes #1446
> fix(1446): updates docs to match _actual_ behaviour of tp.file.folder()

- src/settings/Settings.ts
Small quality of life issues related to folder templates:
1. Change the "+" button to be the same as the other "Add" buttons on the page (resolves #1428).
2. There were two headers being created for the "Folder templates" section; remove the duplicate.
3. The folder templates section is only visible if templates can be triggered on file create, but the toggle is further up in the settings. Move the Folder Templates section to be directly underneath the toggle so the user can easily see what changed.
> Streamline folder template UX

- src/handlers/CommandHandler.ts
Fixed bug where "insert" commands were added without a prefix, but removed with a prefix (see #1480; resolves #1481).
> Fix insert command removal

- src/handlers/CommandHandler.ts
The name of a custom command, which inserts or creates a template, shows now the title of the template instead of its path, which improves readability in the command palette.
> Cleaner display of custom hot key in command palette

- src/core/Templater.ts
- src/core/functions/FunctionsGenerator.ts
- src/core/functions/internal_functions/InternalFunctions.ts
- src/core/functions/internal_functions/InternalModule.ts
I added functionality to create a backup of the current config before switching to a new one when creating a new file with ``create_new_note_from_template`` and reload it after the new file is created. 
This fixes #1554 
I tested it with an extended example from the bug
```
<%*
console.log('This message was before')
await tp.file.create_new("MyFileContent", "MyFilename", false, tp.file.folder(true))
console.log(`I'm on Original: ${tp.file.path(true)}`)
%>
```
File get's created and console prints as expected.
With current master: 
With my changes:
> Fix tp.file.create_new() does not return to original context
