SilentVoid13/Templater

- README.md
- src/internal_templates.ts
Hey, 
Added a new internal template to get an image based on the current note title. Also edited the Readme to include the new template and edited the description for the random image templater
> Added title image internal template

- docs/docs/internal-variables-functions/internal-modules/date-module.md
- docs/docs/internal-variables-functions/internal-modules/file-module.md
- docs/docs/internal-variables-functions/internal-modules/frontmatter-module.md
- docs/docs/internal-variables-functions/internal-modules/system-module.md
- docs/docs/internal-variables-functions/overview.md
- docs/sidebars.js
- src/InternalTemplates/InternalTemplateParser.ts
- src/InternalTemplates/system/InternalModuleSystem.ts
- src/InternalTemplates/system/PromptModal.ts
- styles.css
Mimics the `window.prompt`, but in obsidian.
Closes #111
> Adding new tp.system module containing tp.system.prompt

- docs/docs/internal-variables-functions/internal-modules/file-module.md
- src/InternalTemplates/file/InternalModuleFile.ts
- src/main.ts
> Upgrading tp.file.include to accept obsidian links

- README.md
- docs/docs/settings.md
- docs/docs/user-functions/overview.md
- package-lock.json
- src/Settings.ts
- src/TemplateParser.ts
- src/UserTemplates/UserTemplateParser.ts
- src/main.ts
> Adding new security toggles in the settings

- docs/docs/introduction.md
Modification date in example was referencing creation_date().
> Fixed modification date in the example

- .gitignore
Small change updating .gitignore to handle MacOS files so that I don't accidentally push a .DS_Store or something stupid like that.
> add macos files to ignore in .gitignore

- src/functions/internal_functions/web/InternalModuleWeb.ts
This PR changes the source for quotes when using `tp.web.daily_quote()` It resolves:
#506 
#505 
#501 
#481 
#473 
And perhaps some others too!
> change qotd source

- src/core/Templater.ts
I would like to hook into these events in my [Creases plugin](https://github.com/liamcain/obsidian-creases). I think they could be useful for others as well.
> [feat] Trigger events on template insertion

- docs/documentation.toml
- src/core/functions/internal_functions/system/InternalModuleSystem.ts
- src/core/functions/internal_functions/system/SuggesterModal.ts
> feat(internaltemplates): Add limit to suggester

- src/core/functions/internal_functions/web/InternalModuleWeb.ts
To be consistent with obsidian sizing of image. See https://help.obsidian.md/How+to/Format+your+notes#Resizing+images
> Update sizing of image

- docs/src/settings.md
I struggled to understand how to enable this feature.  [Others struggled with the same thing.](https://forum.obsidian.md/t/folder-templates/28681)
And then I stumbled on the solution by just toggling various settings on and off.
Hopefully this will help others who also have trouble finding where the `Folder Templates` setting is.
> more clarification on Folder Templates

- src/core/functions/internal_functions/web/InternalModuleWeb.ts
Add try/catch to:
- daily quote
- random image
This should prevent them from causing full pages to fail.
> fix: add try/catch logic to web commands

- src/core/Templater.ts
This reverts commit c85de3ef1d332685a74a4607658179f6f1415a8e.
> Revert "fix: change `activeLeaf` to `getLeaf` (#787)"

- src/core/functions/user_functions/UserScriptFunctions.ts
- src/editor/Autocomplete.ts
- src/settings/suggesters/FileSuggester.ts
A bunch of random fixes for errors that popped up after merging last round of pull requests.
> fix: post merge errors

- src/core/functions/user_functions/UserScriptFunctions.ts
- src/editor/Autocomplete.ts
- src/settings/suggesters/FileSuggester.ts
I made a mistake when cutting the last release...
> chore: fix bad revert

- docs/src/internal-functions/internal-modules/date-module.md
- docs/src/internal-functions/internal-modules/file-module.md
- docs/src/internal-functions/internal-modules/frontmatter-module.md
- docs/src/internal-functions/internal-modules/system-module.md
- docs/src/internal-functions/internal-modules/web-module.md
Reverts SilentVoid13/Templater#856
> Revert "Escape apostrophes and keywords in examples in docs closes #852"

- src/editor/CursorJumper.ts
implements FR #884.
tested locally on my device and seems to work fine.
> Jumping cursor loc. enters insert mode (#884)

- package.json
- src/editor/Editor.ts
Closes #854; Closes #491
cc: @shabegom
> feat: enable syntax highlighting in cm6

- styles.css
Add missing comma in styles.css. PR for [#1008](https://github.com/SilentVoid13/Templater/issues/1008) @jaymaleoca
> Add missing comma in styles.css

- docs/src/commands/overview.md
Removed incorrect number, clarified a bit.
> doc: update command utilities prose

- src/handlers/FuzzySuggester.ts
> Fix first letter of suggest modal being cut off

- src/core/functions/internal_functions/system/PromptModal.ts
Fixes: https://github.com/SilentVoid13/Templater/issues/1120
> Prompt Autofocus Input

- docs/src/internal-functions/contribute.md
PR updates the `InternalModuleDate.ts`, `InternalModule.ts` references.
> docs: update source references

- src/handlers/CommandHandler.ts
- src/settings/Settings.ts
- Fix bug where the hotkey search isn't filtered to the command
- Changed the hotkey search to be filtered by template (not inserts in general)
- Generate create command as well as insert command (Resolves #1361)
> Add insert hotkey setting

- src/core/functions/user_functions/UserScriptFunctions.ts
This PR adds support for exporting multiple user-defined functions from a single script file using the pattern:
```js
module.exports = {
fn1: () => "...",
fn2: (tp) => "..."
};
```
Previously, Templater only supported a single default-exported function per script file, which limited how utility logic could be grouped.
This change enables better organization, maintainability, and flexibility for advanced Templater users.
- Modified UserScriptFunctions.load_user_script_function() to support both:
- a single exported function (as before)
- or an object of multiple functions, each of which can be used as tp.user.scriptName.functionName()
- Type-checked to ensure all values exported are functions
- Preserves backward compatibility with existing single-function user scripts
Closes #1607 …
> feat: support object-style module.exports for user scripts

- docs/documentation.toml
- src/core/functions/internal_functions/system/InternalModuleSystem.ts
- src/core/functions/internal_functions/system/MultiSuggesterModal.ts
- styles.css
> feat: add `tp.system.multi_suggester`
